version: '3.8'

services:
  backend:
    build: ./backend
    command: npm run start:dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:3000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevent local node_modules from overwriting container's
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://backend:3000/api/
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15 # Specify PostgreSQL version
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-cfdi_saas_dev}
      - POSTGRES_USER=${POSTGRES_USER:-cfdi_saas_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-supersecretdevpassword} # Use environment variable or secrets
    ports:
      - "5432:5432" # Expose default PostgreSQL port (optional, for direct access)
    restart: unless-stopped

volumes:
  postgres_data:
